name: qg_stock_take_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  awesome_dio_interceptor: ^1.0.0
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  path: ^1.8.3
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: PFBeauSansPro
      fonts:
        - asset: fonts/PFBeauSansPro-Regular.ttf
